# Generated by Django 6.0.1 on 2026-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_email_status',
            field=models.CharField(default='not_sent', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('sumup', 'SumUp'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('amazon_pay', 'Amazon Pay'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('manual', 'Manual')], default='sumup', max_length=20),
        ),
    ]
