# Generated by Django 6.0.1 on 2026-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentwebhooklog_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
