# Generated by Django 6.0.1 on 2026-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymenttransaction_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='provider',
            field=models.CharField(default='stripe', max_length=20),
        ),
    ]
