# Generated by Django 6.0.1 on 2026-07-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentwebhooklog_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='hosted_checkout_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
