# Generated by Django 6.0.1 on 2026-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_paymenttransaction_hosted_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('sumup', 'SumUp'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
