# Generated by Django 6.0.1 on 2026-07-12 10:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default SaaS finance assumptions', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('hosting_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=8)),
                ('database_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8)),
                ('storage_backup_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=8)),
                ('email_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=8)),
                ('monitoring_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('software_tools_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8)),
                ('marketing_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('accounting_admin_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8)),
                ('free_user_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=8)),
                ('plus_user_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('0.85'), max_digits=8)),
                ('professional_user_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('1.40'), max_digits=8)),
                ('enterprise_user_monthly_cost', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=8)),
                ('enterprise_batch_delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=8)),
                ('ai_cost_per_validation', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), max_digits=8)),
                ('generated_cv_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=8)),
                ('payment_percent_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0290'), help_text='Use 0.0290 for 2.9%.', max_digits=5)),
                ('payment_fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=8)),
                ('cash_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_accrual_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Use 0.1900 for 19%. Leave 0 during MVP testing.', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial assumption',
                'verbose_name_plural': 'Financial assumptions',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
