# Generated by Django 6.0.1 on 2026-08-19 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceFeedConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('sumup', 'SumUp'), ('bank_csv', 'Bank CSV'), ('xero', 'Xero'), ('quickbooks', 'QuickBooks'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('account_reference', models.CharField(blank=True, help_text='Non-secret merchant/account label only.', max_length=120)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Non-secret mapping options only; keep API keys in environment variables.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
                'permissions': [('sync_finance_feed', 'Can synchronize finance feeds')],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('income', 'Money in'), ('expense', 'Money out')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import', 'CSV/accounting import'), ('provider', 'Connected provider'), ('recurring', 'Recurring schedule')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('forecast', 'Forecast'), ('recorded', 'Recorded'), ('reconciled', 'Reconciled'), ('void', 'Void')], db_index=True, default='recorded', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('evidence_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['direction', 'status', '-occurred_on'], name='finance_entry_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='finance_entry_amount_gte_0'), models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('provider', 'external_reference'), name='unique_finance_provider_reference')],
            },
        ),
    ]
