# Generated by Django 6.0.1 on 2026-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_last_reset_alter_userprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('microsoft', 'Microsoft'), ('github', 'GitHub')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('is_configured', models.BooleanField(default=False, help_text='Enable after OAuth client ID, secret, callback URL, and scopes are configured.')),
                ('icon_label', models.CharField(blank=True, help_text='Short label shown in the button, e.g. G or in.', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social login provider',
                'verbose_name_plural': 'Social login providers',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
