# Generated by Django 6.0.1 on 2026-08-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_monthly_usage_and_plan_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_signature_mode',
            field=models.CharField(choices=[('personal', 'Personal / company signature'), ('system', 'MyValidCV system-generated email')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
