# Generated by Django 6.0.1 on 2026-08-19 18:05

from django.db import migrations, models


def mark_seeded_demo_profiles(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(user__username__startswith='demo_').update(is_test_data=True)
    UserProfile.objects.filter(user__username='mvcv_demo').update(is_test_data=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Exclude this account and its related records from production KPIs.'),
        ),
        migrations.RunPython(mark_seeded_demo_profiles, migrations.RunPython.noop),
    ]
