# Generated by Django 6.0.1 on 2026-07-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atsresult',
            options={'ordering': ['-created_at']},
        ),
    ]
