# Generated by Django 6.0.1 on 2026-07-08 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_atsresult_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ats_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cv', to='ats.atsresult')),
                ('original_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_versions', to='ats.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File')], default='text', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='job_roles/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reminders', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='ats.jobrole')),
            ],
            options={
                'ordering': ['reminder_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='atsresult',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='ats.jobrole'),
        ),
    ]
