# Generated by Django 6.0.1 on 2026-07-10 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_enterprisebatch_enterprisecandidateresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atsresult',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='atsresult',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='atsresult',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='atsresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_valid_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cv',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid CV'), ('rejected', 'Rejected')], default='valid', max_length=20),
        ),
        migrations.CreateModel(
            name='CVStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('storage_limit', models.PositiveBigIntegerField(default=10485760)),
                ('used_storage', models.PositiveBigIntegerField(default=0)),
                ('auto_delete_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV Storage',
                'verbose_name_plural': 'CV Storage',
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='ats.cvstorage'),
        ),
    ]
