# Generated by Django 6.0.1 on 2026-07-14 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_backfill_cv_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicationreminder',
            index=models.Index(fields=['user', 'is_sent', 'reminder_date'], name='reminder_user_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='atsresult',
            index=models.Index(fields=['user', '-created_at'], name='result_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisebatch',
            index=models.Index(fields=['user', '-created_at'], name='batch_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcv',
            index=models.Index(fields=['user', '-created_at'], name='gencv_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['user', '-created_at'], name='job_user_created_idx'),
        ),
    ]
