# Generated by Django 6.0.1 on 2026-07-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0008_generatedcoverletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('normalized_name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('certification', 'Certification'), ('licence', 'Licence'), ('membership', 'Membership'), ('training', 'Training')], default='certification', max_length=30)),
                ('issuing_body', models.CharField(blank=True, max_length=160)),
                ('is_license', models.BooleanField(default=False)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated alternative names.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['normalized_name'], name='qual_normalized_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('normalized_title', models.CharField(max_length=160)),
                ('seniority_level', models.CharField(choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], default='mid', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated alternative role titles.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='ats.jobfamily')),
            ],
            options={
                'ordering': ['job_family__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplateQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('optional', 'Optional')], default='required', max_length=20)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='ats.qualification')),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_requirements', to='ats.roletemplate')),
            ],
            options={
                'ordering': ['role_template', 'importance', 'qualification__name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('normalized_name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('domain', 'Domain'), ('soft', 'Soft'), ('tool', 'Tool'), ('process', 'Process'), ('language', 'Language')], default='domain', max_length=30)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated alternative names.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['normalized_name'], name='skill_normalized_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('optional', 'Optional')], default='required', max_length=20)),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='ats.roletemplate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='ats.skill')),
            ],
            options={
                'ordering': ['role_template', 'importance', 'skill__name'],
            },
        ),
        migrations.AddIndex(
            model_name='roletemplate',
            index=models.Index(fields=['normalized_title'], name='role_normalized_idx'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('job_family', 'normalized_title', 'seniority_level'), name='unique_role_template_level'),
        ),
        migrations.AddConstraint(
            model_name='roletemplatequalification',
            constraint=models.UniqueConstraint(fields=('role_template', 'qualification'), name='unique_role_qualification'),
        ),
        migrations.AddConstraint(
            model_name='roletemplateskill',
            constraint=models.UniqueConstraint(fields=('role_template', 'skill'), name='unique_role_skill'),
        ),
    ]
