# Generated by Django 6.0.1 on 2026-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0011_cvbulletsuggestion_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisebatch',
            name='email_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisebatch',
            name='email_sending_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisebatch',
            name='mandatory_requirements',
            field=models.TextField(blank=True, help_text='One objective must-have skill, experience, licence, certification, or legal eligibility requirement per line.'),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='email_subject',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='mandatory_matched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='mandatory_missing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='mandatory_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Awaiting human review'), ('shortlisted', 'Shortlisted'), ('criteria_failed', 'Does not meet criteria'), ('mandatory_failed', 'Missing mandatory requirements')], default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='enterprisecandidateresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
