# Generated by Django 6.0.1 on 2026-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0012_enterprisebatch_email_authorized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisebatch',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
