# Generated by Django 6.0.1 on 2026-08-19 12:14

import django.db.models.deletion
import django.utils.timezone
import growth.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('payments', '0007_alter_paymenttransaction_hosted_checkout_url'),
        ('subscriptions', '0003_alter_subscriptionplan_daily_analysis_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending payment'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_purchases', to='governance.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_purchases', to='subscriptions.subscriptionplan')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_purchases', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_bulk_purchase', 'Can approve bulk purchases')],
            },
        ),
        migrations.CreateModel(
            name='AccessVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=growth.models.generate_voucher_code, max_length=40, unique=True)),
                ('campaign_name', models.CharField(blank=True, max_length=180)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('redemptions', models.PositiveIntegerField(default=0)),
                ('allowed_email_domain', models.CharField(blank=True, max_length=180)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='governance.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_vouchers', to='subscriptions.subscriptionplan')),
                ('bulk_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='growth.bulkpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('issue_access_voucher', 'Can issue bulk-access vouchers')],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn'), ('meta', 'Facebook / Instagram'), ('tiktok', 'TikTok'), ('email', 'Email'), ('organic', 'Organic / content')], max_length=30)),
                ('objective', models.CharField(max_length=180)),
                ('audience_summary', models.TextField(blank=True)),
                ('content_brief', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Awaiting review'), ('approved', 'Approved'), ('published', 'Published'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_campaign', 'Can approve marketing campaigns'), ('publish_campaign', 'Can publish approved marketing campaigns')],
            },
        ),
        migrations.CreateModel(
            name='CampaignApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes', 'Changes requested'), ('rejected', 'Rejected')], max_length=20)),
                ('campaign_version', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='growth.marketingcampaign')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('approved', 'Approved'), ('active', 'Active'), ('renewal', 'Renewal'), ('closed', 'Closed')], db_index=True, default='prospect', max_length=20)),
                ('commission_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed fee'), ('percent', 'Percentage')], default='none', max_length=12)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('agreement_reference', models.CharField(blank=True, max_length=120)),
                ('agreement_starts_at', models.DateField(blank=True, null=True)),
                ('agreement_ends_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partners', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='governance.organisation')),
            ],
            options={
                'permissions': [('approve_partner', 'Can approve partner agreements')],
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn'), ('meta', 'Meta / Facebook'), ('tiktok', 'TikTok'), ('google_analytics', 'Google Analytics'), ('search_console', 'Google Search Console')], max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('external_account_hint', models.CharField(blank=True, max_length=180)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Non-secret configuration only.')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('configure_provider', 'Can configure external providers')],
            },
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_days', models.PositiveIntegerField(default=30)),
                ('self_referrals_allowed', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programme', to='governance.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('landing_path', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=180)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_reference', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_attributions', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='growth.referralpartner')),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('payable', 'Payable'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction')),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='growth.referralattribution')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='growth.referralpartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_commission', 'Can approve partner commissions')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=180)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='governance.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['name', '-occurred_at'], name='growth_event_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('social_login', 'Social login'), ('marketing', 'Marketing communications'), ('analytics', 'Analytics'), ('partner_reporting', 'Partner reporting'), ('advertising', 'Advertising audiences')], db_index=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('policy_version', models.CharField(max_length=40)),
                ('is_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_granted'], name='consent_user_purpose_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_records', to='growth.accessvoucher')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'user'), name='unique_voucher_user_redemption')],
            },
        ),
    ]
