# Generated by Django 6.0.1 on 2026-08-19 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
        ('payments', '0007_alter_paymenttransaction_hosted_checkout_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('partner', 'transaction'), name='unique_partner_transaction_commission'),
        ),
    ]
