# Generated by Django 6.0.1 on 2026-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0002_commissionentry_unique_partner_transaction_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpurchase',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='providerconnection',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
