# Generated by Django 6.0.1 on 2026-08-28 13:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_bulkpurchase_version_partnerprofile_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='commissionable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='matures_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referralattribution',
            name='consent_source',
            field=models.CharField(default='affiliate_consent', max_length=30),
        ),
        migrations.AddField(
            model_name='referralattribution',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='referralpartner',
            name='commission_hold_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='referralpartner',
            name='minimum_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='referralpartner',
            name='terms_version',
            field=models.CharField(default='affiliate-v1', max_length=40),
        ),
        migrations.CreateModel(
            name='AffiliateAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(max_length=40)),
                ('legal_name', models.CharField(max_length=180)),
                ('country', models.CharField(help_text='ISO two-letter country code.', max_length=2)),
                ('approved_channels', models.JSONField(blank=True, default=list)),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_acceptances', to='growth.referralpartner')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'terms_version'), name='unique_partner_terms_acceptance')],
            },
        ),
    ]
