# Generated by Django 6.0.1 on 2026-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0004_commissionentry_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(choices=[('social_login', 'Social login'), ('marketing', 'Marketing communications'), ('analytics', 'Analytics'), ('partner_reporting', 'Partner reporting'), ('advertising', 'Advertising audiences'), ('affiliate_tracking', 'Affiliate referral tracking')], db_index=True, max_length=30),
        ),
    ]
