# Generated by Django 6.0.1 on 2026-08-28 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_alter_consentrecord_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180)),
                ('applicant_type', models.CharField(choices=[('creator', 'Content creator'), ('publisher', 'Publisher or website'), ('career_adviser', 'Career adviser'), ('agency', 'Agency'), ('university', 'University or college'), ('job_fair', 'Job fair or event'), ('charity', 'Charity or career service'), ('public_sector', 'Public-sector service'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('website', models.URLField(blank=True)),
                ('public_profiles', models.TextField(blank=True, help_text='One public profile URL per line.')),
                ('audience_size', models.PositiveIntegerField(default=0)),
                ('audience_countries', models.CharField(max_length=240)),
                ('engagement_evidence', models.TextField()),
                ('audience_description', models.TextField()),
                ('proposed_channels', models.JSONField(default=list)),
                ('promotion_plan', models.TextField()),
                ('previous_experience', models.TextField(blank=True)),
                ('genuine_audience_confirmed', models.BooleanField(default=False)),
                ('compliance_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('meeting_requested', 'Meeting requested'), ('meeting_scheduled', 'Meeting scheduled'), ('changes', 'Changes requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30)),
                ('meeting_status', models.CharField(choices=[('not_scheduled', 'Not scheduled'), ('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_scheduled', max_length=20)),
                ('meeting_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('meeting_notes', models.TextField(blank=True)),
                ('owner_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_affiliate_application', 'Can review affiliate applications')],
            },
        ),
    ]
