# Generated by Django 6.0.1 on 2026-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
