# Generated by Django 6.0.1 on 2026-08-19 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_organisation_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['status', 'organisation_type'], name='org_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['user', 'is_active'], name='org_member_user_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['organisation', 'is_active'], name='org_member_org_idx'),
        ),
    ]
