# Generated by Django 6.0.1 on 2026-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_stripe_billing_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='daily_analysis_limit',
            new_name='monthly_analysis_limit',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_analysis_limit',
            field=models.PositiveIntegerField(default=5, help_text='Monthly CV-to-job validation allowance.'),
        ),
    ]
